#!/bin/sh
set -eu

# RUN
# Swift/T runner script
# Sets up paths and runs Swift/T

set -x

THIS=$( readlink --canonicalize $( dirname $0 ) )
export EMEWS_PROJECT_ROOT=$( readlink --canonicalize $THIS/.. )
EQPy=$( readlink --canonicalize $EMEWS_PROJECT_ROOT/../../src )

export PYTHONPATH=$EMEWS_PROJECT_ROOT/python:$EQPy
export TURBINE_RESIDENT_WORK_WORKERS=1

swift-t -n 3 -p -I $EQPy -r $EQPy \
        $EMEWS_PROJECT_ROOT/swift/workflow.swift --algorithm="algorithm"
