#!/bin/sh
set -eu

# RUN
# Runs the GA0 workflow

PROCS=${PROCS:-3}

set -x

THIS=$( readlink --canonicalize $( dirname $0 ) )
export EMEWS_PROJECT_ROOT=$(  readlink --canonicalize $THIS/.. )
EQPy=$( readlink --canonicalize $EMEWS_PROJECT_ROOT/../../src )

export PYTHONPATH=$EMEWS_PROJECT_ROOT/python:$EQPy
export TURBINE_RESIDENT_WORK_WORKERS=1 # Number of workers of this type
# export SWIFT_PATH=$EMEWS_PROJECT_ROOT/Tcl/Tcl-Task

# which swift-t

swift-t -n $PROCS -p -I $EQPy -r $EQPy \
        $EMEWS_PROJECT_ROOT/swift/workflow.swift $*
